Feature:I am going to validate my website functionalities

Scenario: Calculator Add functionality testing
Given I will navigate to Calc Site
When I add two numbers "4" and "7"
Then the output displayed should be "8"

Scenario: Calculator Add functionality testing
Given I will navigate to Angular js page
When I click on header link
And you will navigate to angular page
Then you will enter "hello" in search box

